// fund/f2han-data.mjs — arbejdsdata for spor/f2han. Kun brugt til at
// generere batch-JSON til db/f2-skriv.mjs. Rører ikke databasen selv.
// Hver post: { robot_id, field_name, caveat (ny), caveat_wording (ny, KUN hvis ændret) }

export const REASON_STRIP = 'spor/f2han: kinesisk term flyttet fra caveat til caveat_wording (allerede bevaret i caveat_wording)';
export const REASON_ADD = 'spor/f2han: kinesisk term flyttet fra caveat til caveat_wording (tilfoejet, var ikke der foer)';
export const REASON_GLOSS = 'spor/f2han: kinesisk gloss fjernet fra caveat — ikke kildetekst (bekraeftet mod raakilde/koaevaevet ikke i kilden), engelsk betydning bevaret';

export const BATCHES = {
  'astrall-dynamics': [
    {
      robot_id: 2186, field_name: 'docking_station', reason: REASON_GLOSS,
      caveat: "Under the fire/emergency-response use-case tab: fully autonomous — high-precision autonomous navigation, fully autonomous charging. The word 'docking' does not appear verbatim; 'fully autonomous charging' is interpreted here as a charging/docking function. Appears in the product page's use-case section, not in the parameters table itself.",
    },
  ],
  cvte: [
    {
      robot_id: 2189, field_name: 'docking_station', reason: REASON_ADD,
      caveat: "Highly autonomous: scheduled start/stop, self-navigation and self-return-to-charge. The news article (same domain) elaborates further (see the docking-station field's second source note). The term 'docking station' does not appear verbatim in either source — 'self-navigation and self-return-to-charge' / 'automatic return-and-charge' is interpreted as referring to an automatic charging facility.",
      caveat_wording: "高度自主 定时启停、自主导航与回充 | 自动返航充电",
    },
  ],
  'galileo-tianjin': [
    {
      robot_id: 2199, field_name: 'payload_walking', reason: REASON_STRIP,
      caveat: "Effective payload. Mapped to walking payload - 'effective, during active use' is interpreted as corresponding to the walking/dynamic load, parallel to Yuejia's explicit 'dynamic load'. An interpretation, not the manufacturer's own word 'walking'.",
    },
    {
      robot_id: 2199, field_name: 'battery_wh', reason: REASON_ADD,
      caveat: "Manufacturer states both Ah and Wh directly (720Wh is NOT calculated by us). Nominal voltage is given separately as 48V.",
      caveat_wording: "\"电池容量: 15AH，720Wh\" \"电池额定电压: 48V\"",
    },
    {
      robot_id: 2200, field_name: 'battery_wh', reason: REASON_ADD,
      caveat: "Battery capacity - identical to the walking C1. Nominal battery voltage 48V.",
      caveat_wording: "\"电池容量: 15AH，720Wh\" \"电池额定电压: 48V\"",
    },
    {
      robot_id: 2201, field_name: 'data_ports', reason: REASON_STRIP,
      caveat: "TypeC replaces the C1/C1-W pair's RS485. 'Interfaces can be expanded as needed' is not a fourth port, just a note on flexibility.",
    },
  ],
  'genisom-ai': [
    { robot_id: 2205, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "Explicit (includes battery). CORRECTED ON SELF-CHECK: this row has no 'approx.' mark before the weight, unlike the measurements just above it in the same table, which ARE marked. An earlier draft of this entry incorrectly set operator '~' on the weight, assuming the whole section shared the same approx. marking — corrected after re-reading the raw JSON." },
    { robot_id: 2205, field_name: 'length', reason: REASON_STRIP,
      caveat: "The axes ARE labelled explicitly by the manufacturer (in order: length, width, height), unlike MicroRoboTech's two entries." },
    { robot_id: 2205, field_name: 'degrees_of_freedom', reason: REASON_GLOSS,
      caveat: "Number of joint motors, not explicitly 'degrees of freedom'. Same interpretation as the Unitree Go2 in this collection." },
    { robot_id: 2205, field_name: 'speed', reason: REASON_STRIP,
      caveat: "A separate limit speed of 5 m/s is also disclosed - not used as the main value, because 'max speed' is the label that corresponds to 'normal maximum speed' elsewhere in this collection." },
    { robot_id: 2205, field_name: 'docking_station', reason: REASON_GLOSS,
      caveat: "Accessories list: charging dock, standard equipment. Confirms a physical charging dock ships as standard, but does NOT confirm autonomous return-to-dock/self-recharging - that term does not appear on L1's page (unlike L2's explicit 'autonomous return-and-recharge function')." },
    { robot_id: 2206, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "Explicit (includes battery). The row has no 'approx.' mark." },
    { robot_id: 2206, field_name: 'data_ports', reason: REASON_STRIP,
      caveat: "The manufacturer claims 7 interface types in total, but 'etc.' makes the list non-exhaustive - only these three categories are named explicitly." },
    { robot_id: 2207, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "Explicit (includes battery). The row has NO 'approx.' mark, unlike the measurements just above it in the same table (same pattern as Gangben L1, corrected there on self-check - checked here from the start after that same error)." },
    { robot_id: 2207, field_name: 'price', reason: REASON_STRIP,
      caveat: "Means 'from'/'starting at': the base-configuration price; options (e.g. the optional charging station above) are added on top." },
    { robot_id: 2208, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In L2-W's own data block - no 'approx.' mark." },
    { robot_id: 2208, field_name: 'autonomy_level', reason: REASON_STRIP,
      caveat: "Qualitative list from L2-W's own feature list. Adds 'Thomas flair' to the special-motions list compared with the base version's list." },
    { robot_id: 2209, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In L2-W Ultra's own data block - same figure as L2-W, no 'approx.' mark." },
    { robot_id: 2209, field_name: 'cameras', reason: REASON_STRIP,
      caveat: "The pixel count (2.07 MP × 2) sits only next to 'the forward stereo camera' in the raw string - the fisheye array's own pixel count is NOT separately disclosed, so 2.07 MP should be read as covering the stereo camera, not necessarily the whole array." },
    { robot_id: 2210, field_name: 'length', reason: REASON_GLOSS,
      caveat: "Outer dimensions, length×width×height - no 'approx.' mark, no operator set." },
    { robot_id: 2211, field_name: 'sdk_languages', reason: REASON_STRIP,
      caveat: "INVESTIGATED, BUT NOT SET. GENISOM AI's GitHub organisation (zsibot) has a repo 'genisom_robot_sdk' (README: Programming Language: C++, Ubuntu 22.04/CMake/GCC/Boost), but the repo has NO GitHub description tying it to a specific product name (unlike 'genisom_L1_sdk', whose description explicitly names the Genisom AI L1 Series). Neither 'M1' nor 'Tongchui' appears in the extracted README text. Using the repo for M1 would be the same kind of name-coincidence-without-evidence that was caught and rejected on L2's ros2 field in the previous round - hence stated as not disclosed rather than a guess." },
    { robot_id: 2211, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In the structured spec table - no 'approx.' mark. CONTRADICTED by the page's own marketing card: approx. 30kg own weight (the lightest in its class), approx. 30kg sustained working load, achieving a near-1:1 load-to-weight ratio, industry-first for quadrupeds. The two figures (41kg vs. 30kg) are the SAME robot's own weight on the SAME page and are in conflict. Rule 9: not silently corrected. The structured table is used as the field value because it is the more specific source (same principle as the rest of the GENISOM entries), but the inconsistency is not explained away." },
    { robot_id: 2211, field_name: 'length', reason: REASON_GLOSS,
      caveat: "NO 'approx.' mark on this row, unlike L1/L2's corresponding measurements. No operator set, per rule 4 (never invent a caveat the manufacturer did not write)." },
    { robot_id: 2211, field_name: 'autonomy_level', reason: REASON_STRIP,
      caveat: "Qualitative list from the manufacturer's feature section, not a rating on a scale. Autonomous navigation is stated explicitly as OPTIONAL ('optional'), not standard." },
    { robot_id: 2212, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In M1 Pro's own spec table (id 497) - identical to the base version, NO 'approx.' mark. CONTRADICTED by the page's site-wide marketing card ('approx. 30kg') - see the top note. Rule 9: not silently corrected." },
  ],
  microrobotech: [
    { robot_id: 2224, field_name: 'docking_station', reason: REASON_STRIP,
      caveat: "The row is called 'Charging Station: Fast Charge' (label/value pair, see caveat_wording). Confirms a charging station exists, but does NOT confirm autonomous return-home/self-charging - unlike GENISOM L2's explicit claim (including autonomous recharge function). Interpreted as 'yes, a charging station exists', not as 'yes, with self-driving recharge'." },
  ],
  xiaomi: [
    { robot_id: 2249, field_name: 'height', reason: REASON_ADD,
      caveat: "The lying-position measurement is also disclosed: 807 x 406 x 206mm. This is a different state than folded and is not comparable to Unitree's folded measurement. The schema has no folded-measurement fields.",
      caveat_wording: "趴下：长度：807mm | 宽度：406mm | 高度：206mm" },
    { robot_id: 2249, field_name: 'lidar', reason: REASON_STRIP,
      caveat: "NO LIDAR MENTIONED. The manufacturer's sensor list has twelve items and none of them is a LiDAR: RealSense D450 depth camera, AI interaction camera, binocular ultra-wide-angle camera, TOF sensor, light sensor, ultrasonic sensor, IMU, GPS module, magnetometer, optical flow sensor, 6-mic ring array, and touch sensor. The field is not marked as 'no', because the manufacturer does not declare the list exhaustive - but the absence is itself informative." },
  ],
  'yuejia-lingdong': [
    { robot_id: 2254, field_name: 'stair_step_continuous', reason: REASON_STRIP,
      caveat: "Climbable step height - the label means step/stair, interpreted here as continuous stair-climbing, not a single obstacle." },
    { robot_id: 2254, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In the 'basic parameters' table. No 'approx.' marker; no indication of with/without battery." },
    { robot_id: 2254, field_name: 'length', reason: REASON_STRIP,
      caveat: "The source's own unit notation is missing an 'm' (see the top note). The axis order (length first) is explicitly labelled by the manufacturer in the column heading 'standing dimensions'." },
    { robot_id: 2254, field_name: 'autonomy_level', reason: REASON_STRIP,
      caveat: "Six yes/no rows from the 'basic parameters' table, all set to 'yes' for the YJ30. A qualitative list, not a level on a scale." },
    { robot_id: 2254, field_name: 'price', reason: REASON_ADD,
      caveat: "Next to a 'buy now' button on the manufacturer's own page.",
      caveat_wording: "￥78000.00 | 立即购买" },
    { robot_id: 2255, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In the 'basic parameters' table." },
    { robot_id: 2255, field_name: 'autonomy_level', reason: REASON_STRIP,
      caveat: "Five yes/no rows from the 'basic parameters' table - one row fewer than the YJ30's table (no 'follow' item here)." },
    { robot_id: 2255, field_name: 'price', reason: REASON_ADD,
      caveat: "Next to a 'buy now' button.",
      caveat_wording: "￥288000.00 | 立即购买" },
    { robot_id: 2256, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In the 'basic parameters' table." },
    { robot_id: 2256, field_name: 'autonomy_level', reason: REASON_STRIP,
      caveat: "Combines the table's five yes/no rows (same pattern as the YJ30Max, no 'follow' item) with the product description's extra communication and data-analysis features." },
    { robot_id: 2256, field_name: 'price', reason: REASON_ADD,
      caveat: "Next to a 'buy now' button - the highest Yuejia price in the catalogue.",
      caveat_wording: "￥358000.00 | 立即购买" },
    { robot_id: 2257, field_name: 'weight', reason: REASON_GLOSS,
      caveat: "In the 'basic parameters' table." },
    { robot_id: 2257, field_name: 'price', reason: REASON_ADD,
      caveat: "Next to a 'buy now' button.",
      caveat_wording: "￥88000.00 | 立即购买" },
  ],
  'yufan-intelligent': [
    { robot_id: 2258, field_name: 'payload_walking', reason: REASON_ADD,
      caveat: "The manufacturer does not distinguish walking from standing payload anywhere on the page. Placed under walking because all product references (e.g. runtime: 15kg loaded, constant-speed walking) concern carrying while moving, not static standing load. Standing payload is therefore not disclosed, not 0.",
      caveat_wording: "最大载荷 约20kg | 15kg带负载匀速行走续航约3.5小时" },
    { robot_id: 2258, field_name: 'compute', reason: REASON_ADD,
      caveat: "All three are marked 'optional' on the front page.",
      caveat_wording: "\"端侧算力\" \"Orin Nano 8GB 最高 67 TOPS AI 算力\" \"Orin NX 8GB 最高 117 TOPS AI 算力\" \"Orin NX 16GB 最高 157 TOPS AI 算力\" \"可选配\"" },
  ],
};
